[Feat] 로그인, 토큰 재발급, 인가 기능 추가
nhnacademy-ta-Aling/aling-gateway pull request #6
Opened 2024-03-06 01:08 UTC by uasaha

2024-03-06 02:37 UTC, SuJeong68 requested changes
제가 생각한 로직과 상이한 부분이 있어 논의 후에 적용하는 것이 좋을 것 같습니다! 수고하셨습니다 ☺️

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/UserLoginGatewayFilterFactory.java
> +    private static final String ID_HEADER = "Login-Id";
커스텀 헤더에는 X- 를 붙여주시는게 좋을거 같아요

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/UserLoginGatewayFilterFactory.java
> +            ModifyRequestBodyGatewayFilterFactory.Config modifyFilterConfig
ModifyRequestBodyGatewayFilter를 사용해야만 하는 이유가 있나요??

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/BandAuthGatewayFilterFactory.java
> +    private static final String X_TEMP_USER_NO = "X-USER-NO";
이 부분은 X-User-No로 해주시고 TEMP라는 단어는 쓰지 않아도 될거같아요.

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/AuthorizationGlobalFilter.java
> +public class AuthorizationGlobalFilter implements GlobalFilter, Ordered {
해당 필터는 인증 게이트웨이 필터와 겹칩니다. 인증에 대해 글로벌하게 처리하는 것은 좋다고 봅니다만 이 필터를 적용하고자 하면 토큰의 만료 여부를 알릴 수 있게 하고, 기존의 게이트웨이 필터를 삭제해야 할 것 같습니다.

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/resources/application.yml
> +        /auth/api/v1/jwt/issue,
이 경로는 테스트를 위한 경로일까요?

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/AuthorizationGlobalFilter.java
> +    private final AuthGlobalFilterProperties authGlobalFilterProperties;
GatewayFilter Config로 담을 수 있는 내용으로 확인됩니다.

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/AuthorizationGlobalFilter.java
> +    public int getOrder() {
properties에서 설정하지 않고 따로 빼서 순서를 적용하신 이유가 있을까요?

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/UserLoginGatewayFilterFactory.java
> +            ModifyRequestBodyGatewayFilterFactory.Config modifyFilterConfig
ModifyRequestBodyGatewayFilter를 사용해 다시한번 필터 처리를 해야하는 이유가 궁금합니다.

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/resources/application.yml
> +        /auth/api/v1/jwt/issue,
테스트를 위해 남겨놓은 경로일까요?

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/UserLoginGatewayFilterFactory.java
> +                                .maxAge(1209600)
만료값을 상수로 빼면 좋을 것 같습니다.

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/UserLoginGatewayFilterFactory.java
> +    private static final String ID_HEADER = "Login-Id";
여러 필터에서 공통적으로 보이는데 property로 만들어서 쓰는건 어떨까요?

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/AuthorizationGlobalFilter.java
> +                jwtUtils.parseToken(accessProperties.getSecret(), token).getSubject());
이 과정에서 예외가 터지면 어떻게 되나요?

2024-03-06 02:37 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/TokenReissueGlobalFilter.java
> +            exchange.getRequest().mutate()
다른 필터와 동일하게 헤더를 지정하게 되어있는데 전체적으로 로직을 정리해서 다시 적용하면 좋을 거 같습니다.

2024-03-06 02:37 UTC, devel0624 commented on src/main/java/kr/aling/gateway/filter/BandAuthGatewayFilterFactory.java
> +    private static final String X_TEMP_USER_NO = "X-USER-NO";
AuthorizationGlobalFilter 의 USER_HEADER 와 같은 의미를 갖는 상수인가요?

2024-03-06 05:42 UTC, uasaha commented on src/main/java/kr/aling/gateway/filter/UserLoginGatewayFilterFactory.java
> +            ModifyRequestBodyGatewayFilterFactory.Config modifyFilterConfig
RequestBody를 수정하는 방법은 이것밖에 없습니다.

2024-03-06 05:51 UTC, uasaha commented on src/main/java/kr/aling/gateway/filter/UserLoginGatewayFilterFactory.java
> +    private static final String ID_HEADER = "Login-Id";
꼭 붙여야 할까요?

2024-03-06 05:51 UTC, uasaha commented on src/main/java/kr/aling/gateway/filter/AuthorizationGlobalFilter.java
> +public class AuthorizationGlobalFilter implements GlobalFilter, Ordered {
만료 여부를 알리면 재발급은 어떻게 처리하는게 좋을까요?

2024-03-06 06:19 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/UserLoginGatewayFilterFactory.java
> +    private static final String ID_HEADER = "Login-Id";
그렇다면 헤더 이름 규칙을 맞추는건 어떨까요?? 다 있거나, 다 없거나?

2024-03-06 07:09 UTC, SuJeong68 commented on src/main/java/kr/aling/gateway/filter/AuthorizationGlobalFilter.java
> +public class AuthorizationGlobalFilter implements GlobalFilter, Ordered {
재발급 필터를 본 후 생각은 한번에 처리하는게 좋다고 생각하는데 다 분리하니까 중복 코드가 늘어나는 거 같았어요.

2024-03-07 05:58 UTC, uasaha commented on src/main/java/kr/aling/gateway/filter/UserLoginGatewayFilterFactory.java
> +    private static final String ID_HEADER = "Login-Id";
일단 다 붙히는걸로 진행할게요

2024-03-08 00:16 UTC, uasaha commented on src/main/java/kr/aling/gateway/filter/BandAuthGatewayFilterFactory.java
> +    private static final String X_TEMP_USER_NO = "X-USER-NO";
수정하였습니다!

2024-03-08 05:46 UTC, uasaha commented on src/main/java/kr/aling/gateway/filter/AuthorizationGlobalFilter.java
> +                jwtUtils.parseToken(accessProperties.getSecret(), token).getSubject());
처리하였습니다.

2024-03-08 07:31 UTC, SuJeong68 approved these changes
수고하셨습니다 👍👍👍

2024-03-08 07:31 UTC, SuJeong68 commented on src/main/resources/application.yml
> +#            - name: Authentication
지우셔도 됩니다 :D

2024-03-08 07:53 UTC, merged